language: generic

sudo: false
dist: trusty

branches:
  only:
  - master

addons:
  apt:
    packages:
    - click
    - jq
    - python3-requests

script:
- "./build-all.sh"

deploy:
  # Push new packages on OpenStore
  - provider: script
    skip_cleanup: true
    script: ./push-on-openstore.sh
  # Push new packages on GitHub releases
  - provider: releases
    skip_cleanup: true
    overwrite: true
    file_glob: true
    file: ./*.click
    api_key:
      secure: Rjsc+IT9Y+GkS276Eq1SCuVFu7L9bQHSl/hQ9YXhc52fZKZ42Eu0Ko3BpVbOoP0vONLTLXhaydJ5rpks1jL7A16UkITSGe5ecro8LLJ28YO1/4/ofNPaOerF+X/Nemq4ei9TFrWKWlC7UdO9DxxlU3kVsoylfnbb9KLPdq9cS8vJv52fHSEDDpvl+ix/wnAS0sz7o80cLnSV0ZFfJ5/WRE3z04GlcQXMk8e/2dq2t/EA0Q77zcA08D+43XoB+xXSEN7Fh6DTVyX1UFd/SvXj6HWlGA1OyiRdQUKOZFgIqn6041G66Vt7eztR4BAOV+NXsDevZvo53br/DDR/NUASWL7hgXCfIJGZ+vjy81DlArlSvVH5Re3MJWUOZ9R/ojpxIOV8HepIdFM84g19+y2AnGVhXBUwuHPjmqztUM550+Gf2NcmBjqZTjQ6cS4gyxqwacHAwTiuQTYuGCt2B6D5k2HiJPt8M4/qYK23eubFsiGaxVAVHvRzsYZ0GwWVGlMofDskEHuQb9nV3qX28gzFpfT5MhAC+xOomYCMlD6oxxS5VxDfb17i8Vd1tlR64023RzXGkJ0/p6ZTQJ1KoIacyDvx+LQQIzDkQp+jiz7xP1pEHvwmNI59KAuPbMW6IEc6penkWoqQs7bEmm6yzamp7jPUYN+UrOcTgfU9eEwlh50=
